{
 "title": "PolkaDot00 Metrics",
 "description": "Polkadot network node metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "query0", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Height of the chain",
   "type": "stat",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "polkadot_block_height", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Networking bytes per second",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[5m])*8",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Node memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Total memory" },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Available memory" }
   ]
  },
  {
   "title": "Node CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"user\"}[1m]))  *100",
     "legendFormat": "User"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"system\"}[1m]))  *100",
     "legendFormat": "System"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])))  *100",
     "legendFormat": "Total"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"iowait\"}[1m]))  *100",
     "legendFormat": "iowait"
    }
   ]
  },
  {
   "title": "Tasks rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(polkadot_tasks_polling_duration_bucket[5m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(polkadot_tasks_polling_started_total[1m]) - rate(polkadot_tasks_polling_duration_count[1m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Peers connected, discovered, and requested",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "polkadot_sub_libp2p_peers_count",
     "legendFormat": "Peers count"
    },
    {
     "expr": "polkadot_sub_libp2p_peerset_num_discovered",
     "legendFormat": "Discovered peers"
    },
    {
     "expr": "polkadot_sub_libp2p_peerset_num_requested",
     "legendFormat": "Requested peers"
    }
   ]
  },
  {
   "title": "Connected peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "polkadot_sync_peers" }
   ]
  },
  {
   "title": "State Cache DB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "polkadot_state_db_cache_bytes", "legendFormat": "{{subtype}}" }
   ]
  },
  {
   "title": "GRANDPA Validator Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(polkadot_finality_grandpa_communication_gossip_validator_messages[5m])",
     "legendFormat": "{{message}}"
    }
   ]
  },
  {
   "title": "State Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "polkadot_state_cache_bytes" }
   ]
  },
  {
   "title": "Queued Blocks (sync)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "polkadot_sync_queued_blocks" }
   ]
  },
  {
   "title": "Number of transactions in the ready queue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "polkadot_ready_transactions_number",
     "legendFormat": "Number of transactions in the ready queue"
    }
   ]
  },
  {
   "title": "Number of Leaves",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "polkadot_number_leaves" }
   ]
  }
 ]
}